const constants = {
  SAVE_TAB: 'SAVE_TAB',
  DELETE_TAB: 'DELETE_TAB',
  FILTER: 'FILTER',
  SETWORD: 'SETWORD',
  SETLIMIT: 'SETLIMIT',
  CLOSETYPE: 'CLOSETYPE',
  REMOVE_ON_OPEN: 'REMOVE_ON_OPEN'
};
export default constants;
